### ISSUE TITLE
Breaks with latest SDK

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/vm_service_client#15]
Dart VM version: 1.22.0-dev.9.1 (Tue Jan 24 02:09:55 2017) on "macos_x64"

See also https://build.chromium.org/p/client.dart.packages/builders/packages-mac-vm_service_client/builds/358/steps/annotated_steps/logs/stdio

**Comment by nex3** [comment]
If the VM service protocol introduces a breaking change, isn't that a bug in the protocol?

**Comment by kevmoo** [comment]
@nex3 I don't know...
