### ISSUE TITLE
Is there a way to log the messages going over-the-wire?

### ISSUE THREAD

**Issue by DanTup** [dart-lang/vm_service_client#29]
I'm trying to debug some issues and it'd be useful to see all of the raw JSON messages going back forth to the VM service. I'm looked through the code but can't see any obvious way to do this - is it possible? (if not, is it a reasonable request?)

**Comment by nex3** [comment]
You can pass an arbitrary `StreamChannel` to [`new VMServiceClient()`](https://www.dartdocs.org/documentation/vm_service_client/latest/vm_service_client/VMServiceClient/VMServiceClient.html), which means you can add logging using things like [`StreamChannel.changeSink()`](https://www.dartdocs.org/documentation/stream_channel/latest/stream_channel/StreamChannel/changeSink.html) and [`StreamChannel.changeStream()`](https://www.dartdocs.org/documentation/stream_channel/latest/stream_channel/StreamChannel/changeStream.html).

**Comment by DanTup** [comment]
I'll take a look at that; thanks!

**Comment by DanTup** [comment]
Not sure if this is exactly what you had in mind, but seems to do the job - thanks 👍 

```dart
final StreamChannel<String> channel = new IOWebSocketChannel.connect(uri)
    .cast<String>()
    .changeStream((Stream<String> stream) => stream.map(debugPrint))
    .changeSink((StreamSink<String> sink) =>
        new StreamController<String>()
          ..stream.listen((String s) => sink.add(debugPrint(s))));
vmService = new VMServiceClient(channel);
```
