### ISSUE TITLE
Add support for `getSourceReport` - now final

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/vm_service_client#6]
The VM Service has now added a stable `getSourceReport` API – it was added at some point in 1.16 SDK

Would be good to expose this API in this package.

**Comment by nex3** [comment]
@johnmccutchan @turnidge: What version of the VM service protocol first included this method? Did it come with any additional methods? There isn't any documentation of this either in the SDK changelog or in the service protocol revision history.

**Comment by kevmoo** [comment]
Looks like it was added in 3.1 - see here https://github.com/dart-lang/sdk/commit/bf385e448c30323d68524df99f7329174f70ceef

**Comment by kevmoo** [comment]
https://codereview.chromium.org/1929063002/

**Comment by pulyaevskiy** [comment]
Wondering if this can be prioritized? This may seem like a low priority but a lot of community package builds are broken because of this and coverage package.
